2021-11-12 08:10:55 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration fullykiosk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ovapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration knmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration readme which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration climate_group which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration grocy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration neerslag which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:10:55 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 08:11:00 WARNING (MainThread) [homeassistant.components.octoprint] The 'octoprint' option near /config/configuration.yaml:14 is deprecated, please remove it from your configuration
2021-11-12 08:11:00 ERROR (MainThread) [homeassistant.components.weather] The buienradar platform for the weather integration does not support platform setup. Please remove it from your config.
2021-11-12 08:11:02 WARNING (MainThread) [homeassistant.components.ssdp] Failed to setup listener for 0.0.0.0: [Errno 98] Address in use
2021-11-12 08:11:04 ERROR (MainThread) [homeassistant.components.binary_sensor] grocy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/config/custom_components/grocy/entity.py", line 57, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 141, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:11:11 ERROR (SyncWorker_10) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:11:11 WARNING (SyncWorker_10) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:11:15 ERROR (MainThread) [homeassistant.components.sensor] grocy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/config/custom_components/grocy/entity.py", line 57, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 141, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:11:20 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform command_line is taking over 10 seconds.
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.curtains_front')|float > 0 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.curtains_front')|float > 0 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:21 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{%- for i in state_attr('sensor.grocy_stock', 'products') %} {%- if i.id == 93 %} {{ i.available_amount | round }} {%- endif %} {%- endfor %}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 398, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1698, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 514, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 400, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: 'NoneType' object is not iterable
2021-11-12 08:11:21 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: 'NoneType' object is not iterable') while processing template 'Template("{%- for i in state_attr('sensor.grocy_stock', 'products') %} {%- if i.id == 93 %} {{ i.available_amount | round }} {%- endif %} {%- endfor %}")' for attribute '_attr_native_value' in entity 'sensor.kattenvoer'
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:11:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:12:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:12:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:12:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:12:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:12:10 ERROR (SyncWorker_8) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:12:10 WARNING (SyncWorker_8) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:12:20 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:12:52 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:13:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:13:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:13:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:13:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:13:10 ERROR (SyncWorker_6) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:13:10 WARNING (SyncWorker_6) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:13:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:13:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:14:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:14:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:14:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:14:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:14:11 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:14:11 WARNING (SyncWorker_2) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:14:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:15:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:15:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:15:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:15:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:15:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:15:10 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:15:10 WARNING (SyncWorker_2) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:15:34 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:16:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:16:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:16:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:16:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:16:07 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:16:11 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:16:11 WARNING (SyncWorker_2) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:16:39 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:17:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:17:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:17:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:17:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:17:11 ERROR (SyncWorker_0) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:17:11 WARNING (SyncWorker_0) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:17:12 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:17:44 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:18:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:18:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:18:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:18:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:18:11 ERROR (SyncWorker_11) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:18:11 WARNING (SyncWorker_11) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:18:17 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:18:49 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:19:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:19:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:19:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:19:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:19:10 ERROR (SyncWorker_10) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:19:11 WARNING (SyncWorker_10) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:19:22 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:19:54 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:20:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:20:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:20:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:20:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:20:11 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:20:11 WARNING (SyncWorker_3) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:20:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:20:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:21:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:21:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:21:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:21:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:21:11 ERROR (SyncWorker_10) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:21:11 WARNING (SyncWorker_10) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:21:30 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:22:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:22:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:22:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:22:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:22:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:22:11 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:22:11 WARNING (SyncWorker_2) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:22:35 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:23:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:23:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:23:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:23:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:23:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:23:11 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:23:11 WARNING (SyncWorker_2) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:23:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:24:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:24:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:24:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:24:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:24:11 ERROR (SyncWorker_1) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:24:11 WARNING (SyncWorker_1) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:24:13 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:24:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:24:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:25:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:25:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:25:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:25:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:25:11 ERROR (SyncWorker_5) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:25:11 WARNING (SyncWorker_5) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:25:20 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:25:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:25:52 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:26:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:26:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:26:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:26:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:26:11 ERROR (SyncWorker_12) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:26:11 WARNING (SyncWorker_12) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:26:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:26:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:27:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:27:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:27:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:27:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:27:11 ERROR (SyncWorker_7) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:27:11 WARNING (SyncWorker_7) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:27:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:28:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:28:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:28:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:28:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:28:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:28:11 ERROR (SyncWorker_9) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:28:11 WARNING (SyncWorker_9) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:28:33 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:29:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:29:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:29:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:29:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:29:05 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:29:11 ERROR (SyncWorker_7) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:29:11 WARNING (SyncWorker_7) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:29:37 ERROR (MainThread) [custom_components.grocy] Update of Shopping_list failed with <Response [500]>
2021-11-12 08:29:37 ERROR (MainThread) [custom_components.grocy] Update of Stock failed with <Response [500]>
2021-11-12 08:29:37 ERROR (MainThread) [custom_components.grocy] Update of Tasks failed with <Response [500]>
2021-11-12 08:29:37 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:30:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:30:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:30:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:30:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:30:04 ERROR (Thread-3) [custom_components.monitor_docker.helpers] [Docker] grocy: Cannot determine CPU usage for container ('system_cpu_usage')
2021-11-12 08:30:04 ERROR (Thread-3) [custom_components.monitor_docker.helpers] [Docker] grocy: Cannot determine memory usage for container ('stats')
2021-11-12 08:30:04 ERROR (Thread-3) [custom_components.monitor_docker.helpers] [Docker] grocy: Raw 'memory_stats' {}
2021-11-12 08:30:04 ERROR (Thread-3) [custom_components.monitor_docker.helpers] [Docker] grocy: Can not determine network usage for container ('networks')
2021-11-12 08:30:04 ERROR (Thread-3) [custom_components.monitor_docker.helpers] [Docker] grocy: No 'networks' found in raw packet
2021-11-12 08:30:04 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1518, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1499, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 192, in emit
    entry = LogEntry(record, stack, _figure_out_source(record, stack, self.hass))
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 99, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
2021-11-12 08:30:07 ERROR (MainThread) [custom_components.grocy] Error fetching grocy data: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)
2021-11-12 08:30:11 ERROR (SyncWorker_1) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:30:11 WARNING (SyncWorker_1) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:30:11 ERROR (SyncWorker_9) [homeassistant.components.command_line] Command failed: /config/scripts/get_recipies.py
2021-11-12 08:30:11 WARNING (SyncWorker_9) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].name }}'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].id}}'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[1].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[2].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[3].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[4].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[5].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[6].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 13') while processing template 'Template("{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].name }}")' for attribute '_attr_native_value' in entity 'sensor.cooking'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 13') while processing template 'Template("{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].id}}")' for attribute 'recipe_id' in entity 'sensor.cooking'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 13') while processing template 'Template("{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[1].split('<br />')[0]|replace('</li>','')}}")' for attribute 'step_1' in entity 'sensor.cooking'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 13') while processing template 'Template("{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[2].split('<br />')[0]|replace('</li>','')}}")' for attribute 'step_2' in entity 'sensor.cooking'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 13') while processing template 'Template("{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[3].split('<br />')[0]|replace('</li>','')}}")' for attribute 'step_3' in entity 'sensor.cooking'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 13') while processing template 'Template("{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[4].split('<br />')[0]|replace('</li>','')}}")' for attribute 'step_4' in entity 'sensor.cooking'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 13') while processing template 'Template("{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[5].split('<br />')[0]|replace('</li>','')}}")' for attribute 'step_5' in entity 'sensor.cooking'
2021-11-12 08:30:11 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 13') while processing template 'Template("{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[6].split('<br />')[0]|replace('</li>','')}}")' for attribute 'step_6' in entity 'sensor.cooking'
2021-11-12 08:30:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:31:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:31:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:31:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:31:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:31:11 ERROR (SyncWorker_2) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:31:11 WARNING (SyncWorker_2) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:31:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].name }}'
2021-11-12 08:31:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].id}}'
2021-11-12 08:31:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[1].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:31:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[2].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:31:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[3].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:31:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[4].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:31:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[5].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:31:11 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 13 when rendering '{{ state_attr('sensor.recipies', 'recepten')[states('input_number.recipe_id')|round].description.split('<li>')[6].split('<br />')[0]|replace('</li>','')}}'
2021-11-12 08:31:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:31:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:31:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:32:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:32:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:32:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:32:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:32:11 ERROR (SyncWorker_10) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:32:11 WARNING (SyncWorker_10) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:32:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:32:21 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:32:54 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:33:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:33:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:33:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:33:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:33:11 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:33:11 WARNING (SyncWorker_3) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:33:30 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:34:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:34:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:34:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:34:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:34:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:34:11 ERROR (SyncWorker_5) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:34:11 WARNING (SyncWorker_5) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:34:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:34:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-12 08:34:54 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'shopping_list_test' trigger: In 'numeric_state' condition: no entity specified
2021-11-12 08:35:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:35:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:35:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:35:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:35:11 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:35:11 WARNING (SyncWorker_4) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:35:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:36:11 ERROR (SyncWorker_5) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:36:11 WARNING (SyncWorker_5) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:36:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:37:11 ERROR (SyncWorker_9) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:37:11 WARNING (SyncWorker_9) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:37:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:38:11 ERROR (SyncWorker_12) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:38:11 WARNING (SyncWorker_12) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:38:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:39:11 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:39:11 WARNING (SyncWorker_4) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:39:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:40:11 ERROR (SyncWorker_0) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:40:11 WARNING (SyncWorker_0) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:40:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:41:11 ERROR (SyncWorker_6) [homeassistant.components.command_line] Command failed: /config/scripts/shopping_items.py
2021-11-12 08:41:11 WARNING (SyncWorker_6) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-12 08:41:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.recipies is taking over 10 seconds
2021-11-12 08:41:36 ERROR (MainThread) [frontend.js.latest.202111080] https://hass.gladsheimr.nl/hacsfiles/lovelace-grocy-chores-card/grocy-chores-card.js:332:15 TypeError: this.entities[i] is null
2021-11-12 08:41:57 WARNING (MainThread) [homeassistant.components.octoprint] The 'octoprint' option near /config/configuration.yaml:14 is deprecated, please remove it from your configuration
2021-11-12 08:42:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:42:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:42:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:42:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 08:42:00 WARNING (MainThread) [homeassistant.components.octoprint] The 'octoprint' option near /config/configuration.yaml:14 is deprecated, please remove it from your configuration
2021-11-12 08:42:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 167, in _on_stop
    await on_stop()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/reconnect_logic.py", line 84, in _on_disconnect
    await self._on_disconnect_cb()
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 291, in on_disconnect
    disconnect_cb()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 289, in remove_listener
    _async_remove_indexed_listeners(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 317, in _async_remove_indexed_listeners
    callbacks[storage_key].remove(job)
KeyError: 'light.hal'
