2021-11-06 08:34:28 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration fullykiosk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration ovapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration knmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration grocy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration climate_group which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration readme which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:28 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration neerslag which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-06 08:34:52 WARNING (MainThread) [homeassistant.components.octoprint] The 'octoprint' option near /config/configuration.yaml:14 is deprecated, please remove it from your configuration
2021-11-06 08:34:53 WARNING (MainThread) [zigpy.zcl] Unknown cluster 61184
2021-11-06 08:34:53 WARNING (MainThread) [zigpy.zcl] Unknown cluster 61184
2021-11-06 08:35:33 ERROR (MainThread) [homeassistant.components.weather] The buienradar platform for the weather integration does not support platform setup. Please remove it from your config.
2021-11-06 08:35:34 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at bragi: Error requesting data from bragi: Cannot connect to host bragi:8343 ssl:default [None]
2021-11-06 08:35:34 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Asgard' for unifi integration not ready yet; Retrying in background
2021-11-06 08:35:38 ERROR (MainThread) [homeassistant.components.binary_sensor] grocy: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/config/custom_components/grocy/entity.py", line 57, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 141, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform command_line is taking over 10 seconds.
2021-11-06 08:35:44 ERROR (SyncWorker_0) [homeassistant.components.command_line] Command failed: /config/scripts/get_shopping_list.py
2021-11-06 08:35:44 WARNING (SyncWorker_0) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.curtains_front')|float > 0 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.curtains_front')|float > 0 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{%- for i in state_attr('sensor.grocy_stock', 'products') %} {%- if i.id == 93 %} {{ i.available_amount | round }} {%- endif %} {%- endfor %}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 398, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1698, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 514, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 400, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: 'NoneType' object is not iterable
2021-11-06 08:35:44 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: 'NoneType' object is not iterable') while processing template 'Template("{%- for i in state_attr('sensor.grocy_stock', 'products') %} {%- if i.id == 93 %} {{ i.available_amount | round }} {%- endif %} {%- endfor %}")' for attribute '_attr_native_value' in entity 'sensor.kattenvoer'
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:35:44 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at bragi: Error requesting data from bragi: Cannot connect to host bragi:8343 ssl:default [None]
2021-11-06 08:35:54 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at bragi: Error requesting data from bragi: Cannot connect to host bragi:8343 ssl:default [None]
2021-11-06 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:36:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:36:05 ERROR (MainThread) [custom_components.hacs] marksie1988/atomic-calendar-revive - 
2021-11-06 08:36:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:36:14 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at bragi: Error requesting data from bragi: Cannot connect to host bragi:8343 ssl:default [None]
2021-11-06 08:36:43 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:36:44 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed: /config/scripts/get_shopping_list.py
2021-11-06 08:36:44 WARNING (SyncWorker_4) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-06 08:36:54 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at bragi: Error requesting data from bragi: Cannot connect to host bragi:8343 ssl:default [None]
2021-11-06 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:37:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:37:15 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:37:43 ERROR (SyncWorker_8) [homeassistant.components.command_line] Command failed: /config/scripts/get_shopping_list.py
2021-11-06 08:37:43 WARNING (SyncWorker_8) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-06 08:37:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:38:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:38:14 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at bragi: Error requesting data from bragi: Cannot connect to host bragi:8343 ssl:default [None]
2021-11-06 08:38:19 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:38:43 ERROR (SyncWorker_6) [homeassistant.components.command_line] Command failed: /config/scripts/get_shopping_list.py
2021-11-06 08:38:43 WARNING (SyncWorker_6) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-06 08:38:51 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:39:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:39:23 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:39:34 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at bragi: Error requesting data from bragi: Cannot connect to host bragi:8343 ssl:default [None]
2021-11-06 08:39:43 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed: /config/scripts/get_shopping_list.py
2021-11-06 08:39:43 WARNING (SyncWorker_4) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-06 08:39:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:40:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:40:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:40:43 ERROR (SyncWorker_9) [homeassistant.components.command_line] Command failed: /config/scripts/get_shopping_list.py
2021-11-06 08:40:43 WARNING (SyncWorker_9) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-06 08:40:54 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at bragi: Error requesting data from bragi: Cannot connect to host bragi:8343 ssl:default [None]
2021-11-06 08:40:59 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.firstcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.feyenoord', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:41:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input 'None' when rendering template '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == (as_timestamp(state_attr('calendar.werkrooster', 'start_time')) |int - (state_attr('input_datetime.lastcall','timestamp'))) | timestamp_custom("%H:%M") }}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-06 08:41:31 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/grocy/entity.py", line 142, in device_state_attributes
    return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/config/custom_components/grocy/json_encode.py", line 26, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProductBarcodeData is not JSON serializable
2021-11-06 08:41:43 ERROR (SyncWorker_4) [homeassistant.components.command_line] Command failed: /config/scripts/get_shopping_list.py
2021-11-06 08:41:43 WARNING (SyncWorker_4) [homeassistant.components.command_line.sensor] Empty reply found when expecting JSON data
2021-11-06 08:41:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 167, in _on_stop
    await on_stop()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/reconnect_logic.py", line 84, in _on_disconnect
    await self._on_disconnect_cb()
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 291, in on_disconnect
    disconnect_cb()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 289, in remove_listener
    _async_remove_indexed_listeners(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 317, in _async_remove_indexed_listeners
    callbacks[storage_key].remove(job)
KeyError: 'light.hal'
